#!/bin/sh

cd / && wget https://github.com/xsmzhzy/portainer/releases/download/1.23.2/public.zip && unzip public.zip
docker run -d --restart=always --name="portainer" -p 9999:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -v /public:/public portainer/portainer:1.23.2
